[package]
name = "async-await"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.1", features = ["async-await-preview"] }
hyper = "0.12"
